project:
  type: book

book:
  title: Quantification of deforestation on Borneo in the last 20 years based on open source geodata
  author: "Robin Pfaff"
  date: "6/27/2023"
  chapters:
    - index.qmd
    - text/03_introduction.qmd
    - text/04_literature_review.qmd
    - text/05_method.qmd
    - text/06_results.qmd
    - text/07_discussion.qmd
    - text/08_annex.qmd
bibliography: bibliography/BA.bib
csl: bibliography/APA_7th.csl
filters: [remove_title.lua]
crossref:
  chapters: true
link-citations: true
colorlinks: true
linkcolor: black
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Arial}
  - \setsansfont{Arial}
  - \usepackage{anyfontsize}
  - \fontsize{11}{16}\selectfont
  - \usepackage{booktabs}
  - \usepackage{graphicx}
  - \usepackage[nottoc]{tocbibind}
  - \usepackage{natbib}
  - \PassOptionsToPackage{table}{xcolor}
  - \usepackage{xcolor}
  - \renewcommand{\bibsection}{}
  - \usepackage[a4paper, top=2.5cm, bottom=3cm, left=2.5cm, right=2.5cm]{geometry}
  - \usepackage{tocloft}
  - \setlength{\cftbeforetoctitleskip}{0pt}
  - \renewcommand{\cftsecleader}{\cftdotfill{\cftdotsep}}
  - \usepackage{scrhack} # Add scrhack to improve compatibility with other packages
  - \usepackage{etoolbox}
  - \makeatletter
  - \patchcmd{\chapter}{\if@openright\cleardoublepage\else\clearpage\fi}{}{}{}
  - \makeatother

nocite: |
  @unep-wcmcProtectedAreaProfile2023
  @hansenHighResolutionGlobalMaps2013
  @tyukavinaGlobalTrendsForest2022
  @turubanovaOngoingPrimaryForest2018
  @danyloMapExtentYear2021
  @potapovGlobalMapsCropland2021
  @potapovGlobal20002020Land2022
format:
  pdf:
    documentclass: scrreprt
    keep-tex: true
    toc: False
    include-before-body:
      - text/00_cover.tex
      - text/01_imprint.tex
    header-includes:
      - \RedeclareSectionCommand[
          beforeskip=12pt plus 1pt minus 1pt,
          afterskip=6pt plus 1pt minus 1pt,
          font=\fontsize{16pt}{20pt}\bfseries\sffamily,
        ]{chapter}
      - \RedeclareSectionCommand[
          beforeskip=10pt plus 1pt minus 1pt,
          afterskip=5pt plus 1pt minus 1pt,
          font=\fontsize{14pt}{18pt}\bfseries\sffamily,
        ]{section}
      - \RedeclareSectionCommand[
          beforeskip=8pt plus 1pt minus 1pt,
          afterskip=4pt plus 1pt minus 1pt,
          font=\fontsize{12pt}{16pt}\bfseries\sffamily,
        ]{subsection}
      - \RedeclareSectionCommand[
          beforeskip=6pt plus 1pt minus 1pt,
          afterskip=3pt plus 1pt minus 1pt,
          font=\fontsize{10pt}{14pt}\bfseries\sffamily,
        ]{subsubsection}
      - \RedeclareSectionCommand[
          beforeskip=4pt plus 1pt minus 1pt,
          afterskip=2pt plus 1pt minus 1pt,
          font=\fontsize{10pt}{12pt}\bfseries\sffamily,
        ]{paragraph}
      - \RedeclareSectionCommand[
          beforeskip=2pt plus 1pt minus 1pt,
          afterskip=1pt plus 1pt minus 1pt,
          font=\fontsize{8pt}{10pt}\bfseries\sffamily,
        ]{subparagraph}

