stateDiagram
    direction LR
    L: Legend<br><small><div class="square"></div>file<br>process
    A: input geotif
    B: buffer
    C: output files
    C: <center><small>output buffer 100m <br> output buffer 200m <br> output buffer 500m <br> output buffer 1000m <br> output buffer 2000m 
    D: input tif
    E: snap raster
    F: mask
    G: output files
    G: <center><small>output buffer 100m <br> output buffer 200m <br> output buffer 500m <br> output buffer 1000m <br> output buffer 2000m 


    A --> B
    D --> E
    D --> F
    B --> C
    C --> E
    E --> F
    F --> G

    class A,C,D,G file
    class B,E,F process
