# Abstract {.unnumbered .unlisted}

The Borneon tropical forests and peatlands play an important ecological and climatic role, due to their vast biodiversity and climate regulation effects. However, they are threatened by forest loss due to land-use change and fires. The deforestation of tropical forests is related to far-reaching implications for water regulation and greenhouse gas emissions.

It is thus of imperative importance for policymakers to have recent quantitative information on the drivers of forest loss to monitor existing and plan future sustainable development initiatives. Thus, this thesis examines deforestation and its causes on Borneo over the past two decades. It addresses annual deforestation rates, land conversion to oil palm plantations and other crops, the impact of the Roundtable on Sustainable Palm Oil (RSPO) label and the impact of infrastructure on deforestation. The analysis is based on open-source geospatial data generated by modern remote sensing techniques which were processed with open-source solutions.

While 395,548km\textsuperscript{2} of Borneo (54.3%) were covered by primary forest in 2001, deforestation has brought this number down to 334,269km\textsuperscript{2} (45.9%) in 2021 with the peak forest loss of 5,881km\textsuperscript{2} in 2016. Annual rates showed a declining trend thereafter to ~2,000km\textsuperscript{2}. However, forest degradation by selective logging was not considered. Forest fires peak in El Niño years and are the major forest loss driver within the otherwise well-preserved protected areas. Oil palm plantations were responsible for 21.4% of all primary forest logging (excluding forest fires) from 2001 - 2013. Primary forest loss in RSPO-certified concessions was almost inexistent, as they are predominantly located on previously cleared land. Other crops only play a minor role in deforestation. Infrastructure doubled over the study period from 10,332km\textsuperscript{2} to 21,789km\textsuperscript{2}. 91.2% of primary forest loss is located within 2000m of newly built up areas underlining its role as a major driver of deforestation.

Boreno has continued to lose significant amounts of primary forest over the past two decades. With the planned relocation of Indonesia's capital to Kalimantan, as well as the El Niño phenomenon magnified by climate change, the challenges for forest conservation will continue to be immense, even as government regulations such as Indonesia's moratorium on primary forest clearing, introduced in 2011, begin to take effect.

