# Introduction {#sec-introduction}

Borneo, the third largest island in the world, is home to extensive tropical forests and peatlands. They have a vital ecological and climatic role on a global scale and are of great socioeconomic value on a national and regional level [@harrisonTropicalForestPeatland2020]. With an estimated 10,000 to 15,000 species of flowering plants, 37 endemic bird and 44 endemic mammal species [@mackinnonEcologyKalimantan1997], Borneo is part of the Sundaland biodiversity hotspot [@myersBiodiversityHotspotsConservation2000]. However, this vast flora and fauna is threatened by land use change, climate change and fire with the IUCN listing 415 species as threatened [@harrisonTropicalForestPeatland2020]. Among them is the humans' closest relative, the critically endangered Borneo Orangutan [_Pongo pygmaeus_, @iucnPongoPygmaeusAncrenaz2016]. In addition to biodiversity loss, these factors also have profound consequences at regional and global levels. Among them are restrained water quality and quantity regulation services and release of GHGs [@foleySolutionsCultivatedPlanet2011]. Because of these far-reaching consequences, measures to halt, protect, or even reverse tropical deforestation have received increased attention. This, for example, through incorporating regulatory standards, corporate voluntary sustainability commitments, protected area networks, economic incentives, and demand-side interventions [@austinWhatCausesDeforestation2019].

Vegetable oil producing crops such as canola, soybean, sunflower, and oil palm occupy ~7.5% of the world's agricultural land with a total annual production of 217 Mt [2020 - 2022 @oecdOECDFAOAgriculturalOutlook2023]. This demand is expected to increase to 310 Mt by mid-century [@byerleeTropicalOilCrop2016], due to the increasing world population and as a renewable resource for biofuel [@abdulmajidSustainablePalmOil2021]. With a share of approximately one-third, palm oil is globally the most widely used vegetable oil [@kamyabElaeisGuineensis2022; @oecdOECDFAOAgriculturalOutlook2023]. Borneo, which is split between the two largest palm oil producers in the world - Malaysia and Indonesia produce 85% of the world's palm oil - is a cultivation hotspot due to its tropical climate and high rainfalls [@kamyabElaeisGuineensis2022]. In addition to oil palm, other crops such as rice, groundnut, cassava, coffee, cocoa, maize, rubber, coconut, and pulpwood are also cultivated in Malaysia and Indonesia [@faoFAOSTATDatabase2023]. However, their harvest areas are subject to much less expansion and therefore, apart from coconut [@meijaardCoconutOilConservation2020], do not pose a major problem in landscape ecology in this region [@potapovGlobalMapsCropland2021]. 

Another driver closely linked to forest loss is expansion of infrastructure [@meijerGlobalPatternsCurrent2018; @sloanHiddenChallengesConservation2019]. Especially in Asia, large infrastructure expansions proceeded in the last two decades [@potapovGlobal20002020Land2022]. Besides forest loss, new infrastructure is also linked to increased hunting pressure and light pollution [@kamyabElaeisGuineensis2022; @lewanzikArtificialLightPuts2014].

Although many recent global datasets provide the basis for analyzing the key drivers of deforestation, the most recent study examining this for Borneo was conducted a decade ago, without focus on other drivers besides oil palm [@gaveauFourDecadesForest2014].

Over the past decade, open source GIS has steadily improved and gained relevance in academia and industry [@mobasheriHighlightingRecentTrends2020; @coetzeeOpenGeospatialSoftware2020]. Combined with open-source geospatial data, which became widely available since 2008 [@zhuBenefitsFreeOpen2019], it promises to have the potential to accelerate the solution of global and interdisciplinary problems [@mobasheriOpensourceGeospatialTools2020; @coetzeeOpenGeospatialSoftware2020]. Moreover, machine learning algorithms allowed classification into land use by recognition of repeating patterns [@crowleyRemoteSensingRecent2020]. These advances have been widely applied for mapping of deforestation [@hansenHighResolutionGlobalMaps2013; @curtisClassifyingDriversGlobal2018] and detection of oil plam [@danyloMapExtentYear2021; @descalsHighresolutionGlobalMap2021].


Building upon these modern open-source datasets, this thesis investigates deforestation and its drivers, within the spatial extent of Borneo, and a temporal scope spanning the past two decades. More precise, the following questions are addressed: (i) what is the yearly extent of deforestation, (ii) which influence did the introduction of the Roundtable for Sustainable Palm Oil (RSPO) have on deforestation rates, (iii) how much existing cropland was converted into oil palm plantations and (iv) how does proximity to infrastructure impact deforestation rates?  Annex ii provides a list of the in-depth questions that help to answer these guiding questions. 

 Considering the global importance of this region, providing answers to these questions is crucial to aid policy makers monitor global initiatives for sustainable development, climate change mitigation, and conservation of biodiversity and ecosystem functions at the regional level of Borneo. These initiatives include the United Nations Framework Convention on Climate Change, the Paris Agreement and COP26 Glasgow Declaration, the Convention on Biological Diversity and the UN Sustainable Development Goals (SDGs). Especially SDGs responsible consumption and production (SDG 12), cilmate action (SDG 13) and life on land (SDG 15), as well as to a smaller extent life under water (SDG 14) and clean water and sanitation (SDG 6). Furthermore, NGOs operating on Borneo (e.g. Borneo Orangutan Survival Foundation, Bruno Manser Fonds, etc.) can use these results for the selection of new projects as well as for communication to raise public awareness on deforestation and its drivers.