# Literature review

## Deforestation {#sec-deforestation}
Forests are among the most important terrestrial ecosystems and are fundamental to all life processes [@zafirahSustainableEcosystemServices2017]. Tropical forests play a more influential role in the climate cycle and various biodiversity processes in comparison to other terrestrial biomes [@zafirahSustainableEcosystemServices2017]. Their ecosystem services include regulation of the water cycle (quality and quantity), carbon storage, natural pest control, climate regulation, pollination and seed dispersal [@nasiForestEcosystemServices2002]. Undoubtedly, they possess the highest biological diversity, with estimates that consider the global share to be more than half [@jenkinsGlobalPatternsTerrestrial2013]. Additionally, tropical forests are also indispensable for social and cultural identity, livelihoods and climate change adaptation and mitigation [@omettoContributionWorkingGroup2022].

However, tropical forests are threatened. Reports estimate that almost half [@hansenHighResolutionGlobalMaps2013], or even nine-tenths [@faoGlobalForestResources2020], of global deforestation is happening in the tropics, of which rainforests have the highest share [@hansenHighResolutionGlobalMaps2013]. In 2010 Gaveau et al. indicated that three-quarters of Borneo was covered with forest in the early 1970s, reducing to only 390,000 km\textsuperscript{2} (52.8%) remaining forested of which 210,000 km\textsuperscript{2} are considered intact [-@gaveauFourDecadesForest2014]. Much of this deforestation is due to conversion to large-scale agricultural plantations (mainly soybeans, oil palm, corn, cotton, and livestock; see @sec-oilpalm), which represents one of the main causes of the decline in species richness in flora and fauna [@omettoContributionWorkingGroup2022; @jaureguiberryDirectDriversRecent2022]. Forests also prevent nutrient runoff and erosion due to their vegetation cover [@sweeneyStreamsideForestBuffer2014]. Subsequently, deforestation can lead to enhanced sedimentation and thus shallower river networks. This in return can cause massive floods during monsoon season [@zafirahSustainableEcosystemServices2017].

The protection of the forest is also important because it serves as CO\textsubscript{2} reservoir. These carbon stocks get released by deforestation and account for 10-15% of anthropogenic GHGs [@houghtonEmissionsCarbonDeforestation2013]. Even if cultivated trees are subsequently grown, they cannot retain the same amount of CO\textsubscript{2} [@waringForestsDecarbonizationRoles2020]. In 2011, as a reaction to the deforestation rates, Indonesia instituted a moratorium on new licenses for oil palm and timber plantations as well as logging on primary forests and peat lands [@buschReductionsEmissionsDeforestation2015]. Busch et al. estimate that an additional 241 - 615 MtCO\textsubscript{2} equivalents could have been saved if the moratorium had already been implemented in 2000 [-@buschReductionsEmissionsDeforestation2015].

Another major problem is forest degradation. Matricardi et al. state that forest degradation in the tropics occurs over even larger areas than it is deforested [-@matricardiLongtermForestDegradation2020]. However, this is much more difficult to measure because it occurs in the forest and leaves a closed canopy, making it challenging to use remote sensing methods.

## Oil palm _(Elaeis guineensis)_  {#sec-oilpalm}

Originating from West Africa, the oil palm _(Elaeis guineensis)_ is the most efficient and important oil-producing crop worldwide, with a lifespan of ~25 years [@kamyabElaeisGuineensis2022]. It has the highest yield in tropical climates with high rainfall [@kamyabElaeisGuineensis2022]. Hence it is successfully cultivated in Malaysia and Indonesia, with yields ranging from 10 to 35 tons of fresh fruit bunch (FFB) per hectare [@kamyabElaeisGuineensis2022]. These two countries produce 85% of the world's palm oil [@kamyabElaeisGuineensis2022; @ritchiePalmOil2021]. @fig-op_yield shows that in less than 20 years global harvest area has almost quadrupled from 8 Mha in 1994 to 29 Mha in 2021 [@faoFAOSTATDatabase2023]. Therefore, it was extensively mapped using the characteristic backscatter response of palm-like trees from remotely sensed data [@descalsHighresolutionGlobalMap2021]. 

While the massive expansion of production capacities over the last decades is associated with economic growth and rapid development, the ecological impact of converting forest into giant oil palm monocultures and the environmental pollution caused by large quantities of by-products, mainly palm oil mill effluent (POME), during oil extraction pose major problems [@kamyabElaeisGuineensis2022]. The revenue from previous logging of old growth forest helps to subsidize the initial plantation costs [@fitzherbertHowWillOil2008]. However, the conversion is estimated to lose up to 45% of species diversity, density and biomass of invertebrate communities [@barnesConsequencesTropicalLand2014]. Moreover, the drainage of peatlands for land preparation causes the release of large amounts of GHGs [@sheilImpactsOpportunitiesOil2009]. These expansions of harvested areas are also closely linked to changing market values [@gaveauSlowingDeforestationIndonesia2022].

Per ton of FFB, 600-700 kg of POME are produced [@kamyabElaeisGuineensis2022]. POME is effluent from the mills and has a high content of chemical oxygen demand (COD), biochemical oxygen demand (BOD) and heavy metals [@hadiyantoPhytoremediationsPalmOil2013]. It also carries large amounts of nutrients such as nitrogen or phosphorus [@jeongPerformanceComparisonMesophilic2014].  This renders it highly toxic to aquatic life forms [@kamyabElaeisGuineensis2022]. Ultimately, this effluent, insufficiently treated in the majority of cases, leads to health risks for the population living along waters with oil palm mills upstream, eventually even affecting crops irrigated with this water [@kamyabElaeisGuineensis2022].

Palm oil has been used mainly in the food (80%) and to a lesser extent in the non-food sector (20%) including biodiesel [@basironOILPALMITS2004]. Today, 68% are used in foods, 27% in industrial applications and 5% is used for bioenergy [@ritchiePalmOil2021]. 87% of the European Union's (EU) palm oil imports in 2017 were processed into biodiesel [@abdulmajidSustainablePalmOil2021]. This demand is expected to increase even more as the EU has solid legislation around biofuel production [@abdulmajidSustainablePalmOil2021]. But global population growth and the simultaneous increase in demand for vegetable oil will also further increase demand in this area.

Thus, the market urgently requires solutions to reduce its environmental impact. One solution to meet the growing demand for palm oil without expanding cropland is to increase oil extraction rates. Nevertheless, despite research in this area, the OERs have stagnated at 19-21% over the past 40 years [@changEconomicPerspectiveOil2003; @chewImprovingSustainabilityPalm2021]. Another option to reduce pressure on land conversion is genomic research to improve yields, with various approaches being taken [@murphyOilPalm2020s2021]. A private producer claims that his research has the potential to increase yields by up to 20% [@simedarbyplantationSimeDarbyPlantation2020]. However, after a remarkable 40% increase in yield from 1994 to 2011, it has since stagnated at 15 tons per hectare (see @fig-op_yield) and such advances take time for implementation due to the ~25 year lifespan of plantations.

![Global harvest area and production of oil palm evolve accordingly, with no yield improvement since 2011 [@faoFAOSTATDatabase2023].](04_literature_review_files/op_yield.png){#fig-op_yield}

In summary, oil palm is an essential crop globally, known for its efficiency and high yields in tropical regions. While it has contributed significantly to economic growth, its expansion has come at the cost of deforestation and pollution, posing challenges to biodiversity and ecosystems. Nonetheless, markets will continue to thrive, requiring new solutions to reduce land use change and innovations in processing.

\newpage

## Labels for sustainable palm oil {#sec-rspo}
Growing concern about the significant forest loss and ecosystem degradation caused by deforestation has brought cultivation of palm oil to public attention. As a result, the Roundtable on Sustainable Palm Oil (RSPO) was established in 2004 to build a market for sustainable palm oil by establishing environmental and social standards for palm oil production [@rspoWhoWeAre2023; @abdulmajidSustainablePalmOil2021]. The RSPO is formed by producers, retailers, investors and social and environmental NGOs, with currently over 5000 members [@rspoWhoWeAre2023]. With a share of 19% of the oil palm market [@ritchiePalmOil2021], it is almost exclusively the only certification standard in global palm oil trade [@murphyOilPalm2020s2021]. Other labels such as the Malaysian Sustainable Palm Oil (MSPO) and the Indonesian Sustainable Palm Oil (ISPO) have little to no share in international markets and focus mainly on smallholders [@murphyOilPalm2020s2021]. RSPO states that compliance with its standards can mitigate the negative impacts of palm oil production on the environment and local communities [-@rspoWhoWeAre2023]. Since 2005 RSPO demands that new plantations must not replace primary forest and a High Conservation Values (HCV) assessment is required for certification, which besides ecological factors, also considers a wide range of social stakeholders, including local communities [@murphyOilPalm2020s2021]. Since 2018, a High Carbon Stock (HCS) report is additionally required, which prohibits clearing for oil palm on HCS classified lands [@rspoRSPOPrinciplesCriteria2018]. Despite public discussion on oil palm, a study on Swiss consumers showed, that only 9% of the participants were aware of the RSPO label [@wassmannPalmOilRoundtable2023].

A major criticism, however, is that if forests are not classified as HCV or HCS RSPO certifications continue to allow logging [@cazzollagattiSustainablePalmOil2019]. In addition, significant tree losses were reported prior to and post-certification [@cazzollagattiSustainablePalmOil2019]. Furthermore, deforestation rates in certified areas are comparable to or even exceed those in uncertified areas, leading Cazzolla Gatti et al. to conclude that sustainable palm oil may not be sustainable [-@cazzollagattiSustainablePalmOil2019]. The criticism from non-governmental organizations is even more staggering. They claim that RSPO auditors commit numerous violations in the licensing process, such as failing to identify indigenous land rights claims, faulty HCV assessments or serious labor abuses [@eiaWhoWatchesWatchmen2015; @greenpeaceinternationalCertifyingDestruction2013].

## Infrastructure {#sec-infrastructure}
Expansion of infrastructure is happening at a high rate across the globe. In the last two decades, the amount of built-up land area has increased by 47%, whereby this rate is even higher in Asia at 73% [@potapovGlobal20002020Land2022]. With an additional 25 million kilometers of paved roads and more than 300,000 kilometers of rail track, translating into a 60% expansion of land transportation infrastructure by 2050 compared to 2010, infrastructure development will continue at a rapid rate [@ieaGlobalLandTransport2013; @lauranceGlobalStrategyRoad2014]. It is estimated that 90% of this growth will take place in developing countries projecting enormous consequences for Borneo [@lauranceGlobalStrategyRoad2014]. 

With deforestation and infrastructure development in remote areas, hunting pressure is intensifying [@kamyabElaeisGuineensis2022], as well as poaching with improved accessibility [@mooreAreRangerPatrols2018]. In addition, the expansion of habitation of humans stimulated by infrastructure developments is leading to an increase in human-wildlife conflicts [@kamyabElaeisGuineensis2022]. 

Not only does new infrastructure increase settlement and thus human density but it is also associated with greater dispersal pressure of invasive species, leading to new corridors such as roads or rail tracks that facilitate their introduction [@mungiRoleSpeciesRichness2021; @darRoadsActCorridors2015]. Moreover, the resulting increase in light pollution affects the behavior of individual animal species, which in turn can influence their ecosystem services, eventually leading to effects of land erosion [@lewanzikArtificialLightPuts2014].

Since large parts of Borneo are covered with forest, new infrastructure projects cut through these areas, separating and isolating large interconnected habitats [@alamgirHighriskInfrastructureProjects2019] and enhancing deforestation nearby [@meijerGlobalPatternsCurrent2018; @sloanHiddenChallengesConservation2019]. Although ecologists agree that habitat loss has far-reaching and detrimental consequences for biodiversity (see @sec-deforestation, @sec-oilpalm), there is disagreement about the impact that fragmentation itself has [@didhamRethinkingConceptualFoundations2012a; @fahrigRethinkingPatchSize2013; @haddadHabitatFragmentationIts2015a; @miller-rushingHowDoesHabitat2019]. Observational studies often focused only on single aspects of fragmentation (e.g., edge, isolation, area) and failed to take in the full context of the complex interconnected structures of habitats [@haddadHabitatFragmentationIts2015a]. However, a comprehensive experiment indicated, that biodiversity in fragmented habitats is reduced from 13% up to 75% [@haddadHabitatFragmentationIts2015a]. More recently, Püttker et al. underlined that biodiversity of forest-dependent animal and, to an even greater extent, plant species are negatively affected by habitat fragmentation, especially through edge effects [-@puttkerIndirectEffectsHabitat2020]. This also applies to Borneo, as many infrastructure projects, including the planned relocation of the Indonesian capital [@lyonsWhyIndonesiaMoving2019], are estimated to have huge impacts on biodiversity [@alamgirHighriskInfrastructureProjects2019].

To sum up, the expansion of infrastructure contributes not only to habitat loss, but also to increased habitat isolation due to fragmentation, increased introduction of invasive species, and light pollution, disturbing the fauna. 

## Other crops

While some studies say that besides oil palm, which accounts for 88% of industrial plantations, pulp wood is the only crop to cover the other 12% [@gaveauRiseFallForest2019]. However, other studies report that groundnut and coconut are also grown in Borneo, but not in the from of industrial plantations [@meijaardCoconutOilConservation2020]. Coconut plantations occur mainly in smallholder form (<4ha) and thus [@meijaardCoconutOilConservation2020], make it challenging to map with remote sensing methods [@descalsHighresolutionGlobalMap2021]. However, it is thought to have almost a fivefold worse impact on biodiversity [@meijaardCoconutOilConservation2020], These results, though, have caused a lot of controversy [@rochmyaningsihClaimThatCoconut2020]. 

In Southeast Asia, the total cropland extent (excluding perennial woody crops) saw only moderate growth. While 172.9 Mha were permanently used as cropland between 2000 and 2003, 184.5 Mha were used between 2016 and 2019 [@potapovGlobalMapsCropland2021]. A gain of 30.9 Mha offsetted a reduction of 19.3 Mha [@potapovGlobalMapsCropland2021]. Nevertheless, due to public awareness and the rapid expansion of harvest area, oil palm has been extensively researched and mapped [@descalsHighresolutionGlobalMap2021], while maps on other crops harvest area distribution are still sparse [@meijaardCoconutOilConservation2020]. 

In summary, due to much smaller expansion of cropland and perennial woody crops, oil palm diminishes the importance of research on other crops in Southeast Asia and thus there are hardly any maps available making use of the advances in remotely sensed data processing (see @sec-remotesensing).

## Advances in remote sensing {#sec-remotesensing}

Since the launch of the Landsat-1 MSS satellite in 1972, an increasingly comprehensive time series database has been built as newly launched satellites have been equipped with more advanced technology [@crowleyRemoteSensingRecent2020]. However, it was not until 2008 that this data was made available through the free and open Landsat data policy [@zhuBenefitsFreeOpen2019]. Combined with the launch of the European Space Agency's open-access Copernicus mission, research from satellite data has exploded in recent years [@zhuBenefitsFreeOpen2019; @crowleyRemoteSensingRecent2020]. This development has also been facilitated by the availability of massive-throughput analysis platforms like the Google Earth Engine implemented in 2010 [@crowleyRemoteSensingRecent2020]. Another crucial achievement was the development of machine learning algorithms that separates the remotely sensed data into meaningful classifications [@crowleyRemoteSensingRecent2020]. Furthermore, machine learning offers unprecedented potential for gaining deeper insights from historical data, as well as filling in gaps in it [@sarafanovMachineLearningApproach2020].

Despite these advancements, many high-resolution land cover and land use (LCLU) datasets [@zanagaESAWorldCover102021; @karraGlobalLandUse2021; @descalsHighresolutionGlobalMap2021], while offering unprecedented detail, do not support multi-decadal analysis [@potapovGlobal20002020Land2022]. However, medium resolution (30m resolution) multidecadal datasets are more widely available [@danyloMapExtentYear2021; @hansenHighResolutionGlobalMaps2013; @potapovGlobalMapsCropland2021; @potapovGlobal20002020Land2022; @turubanovaOngoingPrimaryForest2018; @tyukavinaGlobalTrendsForest2022].