# Results





#### Questions





#### General Forest loss
1. How much forest area was lost yearly and in total?
2. How much forest area was lost due to forest fires yearly and in total?
3. How much new build up areas was created on forest loss areas (2020 compared to 2000)?
4. How much new build up areas was created on forest-fire loss areas (2020 compared to 2000)?
5. How much forest gain (area) occured on forest fire areas (2001 - 2012)?
6. How much forest was lost in protected areas yearly?
 --> carry out all of them with primary forests as well

#### Oil Palm related
1. How much new oil palm plantation area occured yearly on forest fire areas?
2. How much new oil palm plantation area occured yearly on non-forest deforested areas?
3. How much new oil palm plantation area occured yearly on deforested areas?
4. How much new oil palm plantation area occured in protected ares?
5. How much new oil palm plantation areo occured on non-forest area? (compared to year 2000 forest cover)
6. How much new oil palm plantation area occured on previos cropland (and other way around)?
7. How much forest area was ganied on previous oil palm plantation area yearly (2000 - 2012)?
8. How much area was used for other crops prior to oil palm plantation, and which?
9. How much area was used for oil palm plantation prior to other crops, and which?

#### Build up areas
1. How much new build up area occured in forest covered area (2020 compared to 2000)?
2. How much new build up area occured in non-forest covered area (2020 compared to 2000)?
3. How much new build up area occured in forest fire area (2020 compared to 2000)?
4. How much new oil palm plantation area occured within 1, 2, 5, 10, and 20 km of newly buld up areas?
5. How much forest area was lost to forest fires within 1, 2, 5, 10, and 20 km of newly buld up areas?
6. How much forest area was lost to non-forest fires deforested areas within 1, 2, 5, 10, and 20 km of newly buld up areas?
7. How much forest area was lost to cropland areas within 1, 2, 5, 10, and 20 km of newly buld up areas?

#### RSPO
???


















For more information, refer to the literature review (@chapmanCompoundingImpactDeforestation2020; @descalsHighresolutionGlobalMap2021).




