# Discussion {#sec-discussion}

## Deforestation {#sec-d_deforestation}

Ongoing deforestation in Borneo continues to threaten valuable biodiversity through further deforestation resulting in habitat loss or degradation. The declining trend of forest loss in recent years (@fig-bardeforestationprimary) suggests that efforts such as the moratorium on logging of primary forests in Indonesia are beginning to have an impact, giving endangered endemic species a chance to be preserved. Nonetheless, the trend in reduced forest loss must be confirmed in the coming years to maintain crucial habitat for species conservation in the long-term. But even if human deforestation continues to decline, the effects of past deforestation contribute to increased fire precursors such as increased temperature, wind speed and potential evapotranspiration and decreased humidity, cloud cover and precipitation [@trancosoConvertingTropicalForests2022]. In addition, rising levels of atmospheric CO\textsubscript{2} are further increasing the risk of wildfires, whilst also being one of the causes for a phenomenon called El Niño [@wangHistoricalChangeNino2019]. This event, caused primarily by unusually warm ocean temperatures, results in significantly higher temperatures during the dry season, causing the soils to become more dry [@nasaIndonesianFiresReturn2023; @wangHistoricalChangeNino2019]. Ultimately, this leads to small-scale fires set by smallholders to clear pasture spreading much more quickly and across a wider area [@nasaIndonesianFiresReturn2023]. Therefore, the small-scale fires occurring all over Borneo can not only be attributed to smallholders, but these small-scale fires can also trigger large-scale fires, which are fueled by the El Niño phenomenon and the reason for the outlier years with a lot more forest fires, including those in protected areas. Nevertheless, the low rates of deforestation in protected areas emphasize their importance. This suggests that additional protected areas could be an important tool to ensure the integrity of the relatively untouched primary forests in the inland of Borneo. Additionally, smallholders should be sensitized or at least alarmed, if an El Nino year approaches, to reduce the risk of future large forest fires, especially close to protected areas.


## Oil Palm

Whilst this thesis allocates ~4 Mha to newly detected oil palm plantations on Borneo from 2001 to 2017, another paper states a higher number with ~ 5.5 Mha for the same period [@gaveauRiseFallForest2019]. Gaveau et al. only defined industrial plantation >90ha on satellite imagery by eye [-@gaveauRiseFallForest2019]. Considering the 4-year detection lag of the remotely sensed dataset and the yearly detection rate in these years (~0.3 Mha), the results coincide. However, the data used here is based on a remote sensing approach and includes smallholder plantations, and therefore it is likely that the newly discovered oil palms are underestimated. This is further supported by the fact that many oil palm plantations are located on deforestation clusters that are not completely covered by oil palms (@fig-map_deforestation_op_fires). Thus, it can be concluded that the numbers on oil palm and subsequently deforestation prior to oil palm plantations are too low. 

Even though Danylo et al. state, that it takes only 2-3 years for newly planted oil palms to be detected [-@danyloMapExtentYear2021], the lag phase in @fig-bar_opdeforestation indicates, that it is 4-5 years. As oil palm plantations in primary forests (0.71 Mha) account for 21.4% of all primary forest logging (excluding forest fires) from 2001 to 2013 (3.31 Mha) and considering the underestimation of new oil palms, it can be concluded, that oil palm is an important driver of primary forest loss on Borneo. Nonetheless, even if other areas of primary forest loss would account for conversion to other industrial plantations, this still makes logging the main driver of primary forest loss. 

The portion of new oil palm on secondary forest loss areas cannot necessarily be attributed to secondary forest loss. Since oil palm plantations need to be replanted (see @sec-oilpalm), but are also categorized as secondary forest, replanting is categorized as secondary forest loss. Additionally, it would be too facile to attribute all of the deforestation solely to palm oil, since it is not known whether oil palm caused deforestation or merely followed the clearing of land [@fitzherbertHowWillOil2008]. For example, some companies used palm oil concessions to obtain permission to log, and thus make money, without cultivating palm oil on the land [@fitzherbertHowWillOil2008]. However, it is not known if this practice still exists and planting of oil palms is reported to be detected immediately after clearing [@gaveauRiseFallForest2019]. In addition, the fine-scaled unorganized patterns for logging (see @fig-map_deforestation_primary) differ strongly from the rectangle, clear edge and large area clearing (see @fig-map_deforestation_op_fires).

Even though plantation expansion has slowed, the recent large price jump (from 601 USD per ton in 2019 to 1276 USD in 2022) is a worrying indicator, that this trend will soon be reversed in the future [@worldbankAveragePricesPalm2023]. This is because the price is closely linked to the expansion of oil palm production [@gaveauSlowingDeforestationIndonesia2022] and thus to environmental issues discussed in @sec-oilpalm.

### RSPO

While, based on the data information given by the RSPO, it remains unclear what an uncertified RSPO concession is, certified concessions represent with 15.8% roughly the share of the RSPO certified palm oil trade (19%, see @sec-rspo). Since most of the concessions are located on predominantly deforested land anyway, it can be said that the palm oil coming from these plantations does not further contribute to a noteworthy loss of primary forest, since no blending takes place in the mills, which is strictly regulated by RSPO regulations [@rspoRSPOPrinciplesCriteria2018]. 

Although primary forests take up a marginal amount of RSPO concessions and much of it is already logged (@sec-resultsrspo), the sharp drop in primary deforestation within certified concessions in 2011 (@fig-RSPO_primaryloss) is still remarkable, as it coincides with the introduction of the Indonesian moratorium of logging in primary forest. Nevertheless, assuming a link here would be highly uncertain due to two factors: i) the small reference area and ii) the availability of RSPO concession data only for Malaysia.

A statement on whether the introduction of the RSPO label has reduced deforestation by palm oil overall cannot be made and would also be an exaggeration since the RSPO has no or at best indirect influence via advising politicians on concessions for new palm oil plantations. In summary, despite the criticism directed at the RSPO (see @sec-rspo), it must be said that at least no more primary forest is being lost for their certified palm oil.

## Infrastructure

If both the built up area and the forest loss datased had 100% accuracy, there should not be any deforestation on built up areas from 2000. Whilst the marginal 0.8% overlap with primary forest clearing confirms high accuracy, the 17.7% with secondary forest cannot be attributed to data inaccuracy (see @fig-forestloss_pie_existing_built_up). The reason for this unexpectedly large number can be assigned to maintenance work of constantly overgrowing vegetation near roads (see annex IV). 

### Buffer 

With almost three-quarters of the Bornean land within 2000 m of infrastructure in 2020, accessibility of remote areas has increased by 92557km \textsuperscript{2} over the study period, leaving only 26.7% of Borneo untouched (@tbl-buffer_op). This increases the pollution pressures described in @sec-infrastructure. However, as the underlying dataset does not separate private roads (e.g. maintenance roads for industrial plantations) from public roads, it remains unclear how much of the increase in accessibility is due to the expansion of public infrastructure versus private development. However, more detailed maps that capture the temporal development of new roads are scarce. Only open street map provides access to historical data going back to 2013, but its completeness depends on the activity of the users and is therefore questionable, especially in early years. Therefore, a new dataset covering infrastructure development (especially roads) in an annual interval would be an important tool for further research in quantifying the impact of new infrastructure. Nevertheless, the relationship between the establishment of new oil palm plantations and deforestation rates could be closely linked to better access through new infrastructure (@tbl-buffer_primary, @tbl-buffer_op). Hence, it is crucial to implement sustainable infrastructure development practices and stringent regulations to mitigate the disturbance effects of future infrastructure projects, especially with respect to the planned relocation of the Indonesian capital to Borneo, where Indonesia has the chance to set new standards for sustainable infrastructure development in the tropics [@spencerImplicationsLargescaleInfrastructure2023]. 

Another often overlooked form of infrastructure are natural waterways, which allow easy access deep into the forests. Thus, the deforestation of primary forest along rivers (see annex V) can also be attributed to (natural) infrastructure.


## Cropland

Due to the small amount of acreage devoted to shrubby crops, their share of deforestation is almost negligible compared to palm oil. However, there are many small wildfires near these croplands, supporting the claim that smallholders are using fire to clear the land near their fields for pasture, which has a high risk of triggering large-scale wildfires (@sec-d_deforestation).

Although other tree crops are grown on Borneo in addition to oil palm, they - even though understudied - certainly do not reach anywhere near the scale of oil palm plantations, with Gaveau et al. reporting that oil palm accounts for 88% of industrial plantations in Borneo [-@gaveauRiseFallForest2019].

## Conclusions

In summary, Borneo continues to be threatened by deforestation, which endangers its unique biodiversity and habitat integrity. Recent figures show a declining trend in forest loss, likely due to initiatives such as the moratorium on logging in Indonesia's primary forests. However, this trend requires continued confirmation to prof long-term conservation efforts. Furthermore, rising atmospheric CO2 levels and the El Niño phenomenon increase forest fire risk. Protected areas play an important role in maintaining primary forests and biodiversity.

The expansion of oil palm cultivation, which is the second largest contributor to primary forest loss after logging, is showing signs of slowing, although the recent rise in palm oil prices is an alarming indicator. Since 2011, virtually no primary forest has been cut down for RSPO-certified palm oil, making it, despite criticism and the lack of alternative labels, the most viable option for sustainably conscious stakeholders at present. Other crops only play a minor role in deforestation. Infrastructure development has substantially improved accessibility to remote areas, which led to increased deforestation, hence calling for sustainable practices and strict regulations for future projects.

In summary, the problem of deforestation in Borneo can only be addressed with a holistic approach that includes sustainable practices, strict regulations, awareness campaigns, and responsible development to protect the exceptional biodiversity within the remaining primary forests.